### ISSUE TITLE
v730: Transformation "DEMO_JSON_XML_TO_UPPER" has no active version

### ISSUE THREAD

**Issue by nununo** [larshp/ABAP-Swagger#12]
ZCL_SWAG->FROM_INPUT uses an object which is not available in my system. Can we downgrade it to an alternative which doesn't use it?
```
        CALL TRANSFORMATION demo_json_xml_to_upper
          SOURCE XML lv_cdata
          RESULT XML lo_writer.
```

**Comment by larshp** [comment]
probably the easiest solution would be to copy the transformation to Z namespace, and include it in git

code is following if you want to try it out:

`<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
               xmlns:sap="http://www.sap.com/sapxsl" version="1.0">
  <xsl:template match="@* | node()">
    <xsl:copy>
      <xsl:apply-templates select="@* | node()"/>
    </xsl:copy>
  </xsl:template>
  <xsl:template match="@*">
    <xsl:attribute name="name">
      <xsl:value-of select="sap:upper-case(.)"/>
    </xsl:attribute>
  </xsl:template>
</xsl:transform>`

**Comment by nununo** [comment]
Hi,

Done.
Since this is my first contribution ever please tell me if I followed the correct procedure,

What I did:
- deleted the project code coming from your repository to start from scratch
- forked the project
- cloned my forked project into my system
- created a branch called "downgrade" (I had to do it directly in GitHub because from abapGit I kept getting a communication error)
- in abapGit switched to that branch
- created the Z object as copy of the standard using the code you provided and downgraded syntax in 3 places.
- staged it and committed
- submitted a pull request

**Comment by larshp** [comment]
it is the correct approach :smile:

**Comment by larshp** [comment]
closing, fixed in https://github.com/larshp/ABAP-Swagger/pull/13
