### ISSUE TITLE
How to make it work

### ISSUE THREAD

**Issue by novastorm123** [larshp/ABAP-Swagger#16]
Hi Lars,
I am unable to decide the list of classes that i have to implement and in which flow to make it work.

**Comment by larshp** [comment]
just install all the objects via abapGit

you can take a look at https://github.com/larshp/abapGitServer on how the framework works, also https://github.com/larshp/todo_logic/tree/web

there is not any documentation yet for this project

**Comment by larshp** [comment]
if you put your code/example on github then I can guide you through the process if you like

**Comment by larshp** [comment]
@novastorm123 did it help?
