### ISSUE TITLE
Grouping of Web Services Under One Name

### ISSUE THREAD

**Issue by thesourav123** [larshp/ABAP-Swagger#25]
Hi @larshp 
 Suppose, we have a Parent SICF Node and several child nodes under it. And if we run the swagger.html extension on the parent node, we should be able to see all the web services below it.( Similar to http://petstore.swagger.io/) . How to achieve that?

**Comment by larshp** [comment]
the swagger UI takes one swagger specification as input, one swagger specification corresponds to one class in ABAP-Swagger

So if you want to group the operations together they have to be in the same class, example: https://github.com/larshp/abapGitServer/blob/master/src/service/zcl_ags_service_rest.clas.abap

![image](https://user-images.githubusercontent.com/5888506/33335646-e2de0680-d46d-11e7-813a-007dd79b6ff5.png)

If you are referring to where it says "default", these are tags, which can be used for grouping operations, these are currently not implemented in ABAP-Swagger

**Comment by thesourav123** [comment]
@larshp Thanks It worked.

**Comment by larshp** [comment]
cool, closing issue, feel free to open another if you have questions or find bugs
