### ISSUE TITLE
Using Local Class Variables in Web Service Methods

### ISSUE THREAD

**Issue by thesourav123** [larshp/ABAP-Swagger#26]
Hi @larshp,
 I am unable to use Local Class Variables in my class due to RETURNING Parameters restriction. With RETURNING addition, only Data Dictionary Types can be declared.

 When i changed it to allow EXPORTING Parameters, it allowed me to use local class variables.
 Now, the problem is, the local types are not interpreted correctly in the BUILD_PARAMETERS method.
 For example, i have a method that takes KUNNR as input and TT_OUTPUT as output.
 So, it gives a DUMP because BUILD_PARAMETERS reads TT_OUTPUT as string, whereas my method is expecting a table type.

To make it work, i had to convert it to JSON string and pass it as output.
Any advice will be appreciated

**Comment by larshp** [comment]
hi, can you help making a small example and put it on github, I'm not sure I understand the setup

**Comment by larshp** [comment]
@thesourav123

**Comment by thesourav123** [comment]
Hi Lars,
 You can close this issue, Its working now.
