### ISSUE TITLE
tags, support for descriptions

### ISSUE THREAD

**Issue by larshp** [larshp/ABAP-Swagger#28]
will require new structure instead of the currently used RT_META

**Comment by thesourav123** [comment]
Is this working now with the new RT_META structure?

**Comment by larshp** [comment]
tags are implemented, but not descriptions, as it will require a breaking change

**Comment by larshp** [comment]
also note the possibility for externaldocs, see https://swagger.io/docs/specification/2-0/grouping-operations-with-tags/

**Comment by BlackmanCC** [comment]
It would be possible to add a member variable to zcl_swag with structure

```
    TYPES:
      BEGIN OF ty_tags,
        tag               TYPE string,
        description       TYPE string,        
        externaldocsurl   TYPE ty_url,
      END OF ty_tags .
    TYPES:
      ty_tags_tt TYPE STANDARD TABLE OF ty_tags WITH DEFAULT KEY .
```


and to define a new importing parameter to contructor of lo_swag or a method SET_TAGS to set tag description.

I think a SET TAGS method would be better.

**Comment by BlackmanCC** [comment]
It would be possible to add a member variable to zcl_swag with structure

```
  types:
    BEGIN OF ty_externaldoc,
        description TYPE string,
        url         TYPE string,
      END OF ty_externaldoc .
  types:
    BEGIN OF ty_tagdescription,
        tag         TYPE string,
        description TYPE string,
        externaldoc TYPE ty_externaldoc,
      END OF ty_tagdescription .
  types:
    ty_tagdescription_tt TYPE STANDARD TABLE OF ty_tagdescription WITH DEFAULT KEY .

```


and to define a new importing parameter to contructor of lo_swag or a method SET_TAGS to set tag description.

I think a SET TAGS method would be better.
