### ISSUE TITLE
downport to NW 7.31?

### ISSUE THREAD

**Issue by JohannesKonings** [larshp/ABAP-Swagger#39]
Pipe is not known on NW 7.31. Can we downport this?

![image](https://user-images.githubusercontent.com/14806640/43099917-010a3a14-8ec4-11e8-9e7f-62381de558c3.png)

This works
![image](https://user-images.githubusercontent.com/14806640/43100497-cb1050e0-8ec5-11e8-84f3-349196113038.png)

**Comment by larshp** [comment]
hmm, thought string templates were part of 702, but perhaps not for this operator position

**Comment by JohannesKonings** [comment]
done with https://github.com/larshp/ABAP-Swagger/pull/40
