### ISSUE TITLE
Installation with abapGit version 1.37.2

### ISSUE THREAD

**Issue by germanysources** [larshp/ABAP-Swagger#43]
The import with abapGit fails. The document zdemo_json_xml_to_upper.xlst.source.xml produces the runtime error cx_sy_ref_is_initial.
The "abapGit" tag in this document is missing. 

The stack trace is attached:
[error_abapgit.txt](https://github.com/larshp/ABAP-Swagger/files/2956683/error_abapgit.txt)

**Comment by larshp** [comment]
update abapGit to latest version,

v1.37.2 is from 2017-06-10

**Comment by germanysources** [comment]
Problem is fixed with the newest version.
