### ISSUE TITLE
Parameter descriptions

### ISSUE THREAD

**Issue by BlackmanCC** [larshp/ABAP-Swagger#59]
Is there a way to read out sap parameter descriptions and show them in swagger ui?

**Comment by larshp** [comment]
I think currently its not implemented, but pull requests welcome

**Comment by BlackmanCC** [comment]
I can implement it, but I do not know if I should.
Parameter descriptions can only be set in class builder SE24 or SE80 and not in ADT.
I could implement it and use field descript of table SEOSUBCOTX. The best way would be to change META structure.

Currently parameters is defined as:

`      ty_parameters_tt TYPE STANDARD TABLE OF seosubcodf WITH DEFAULT KEY .
`

I could change ist to an own structure with only necessary fields and field SEOSUBCOTX-DESCRIPT.  I would use default system language and get it from function RSRA_GET_DEFAULT_LANGUAGE.

What do you think?

**Comment by larshp** [comment]
I think its low priority, personally I typically delete all the descriptions because they are usually wrong 😁
