### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by All2in** [larshp/ABAP-Swagger#64]
Hi there!

I tried to assign a technical User in SICF to enable external Users to see the Page and authorize via the button if they want to test, but in Debugging I always see the technical User in sy-uname. So if the User needs to Log On with his SAP User to reach the Page, the Authorize Button is not really needed. Is there a way to remove the button? 

regards,
Alex

**Comment by larshp** [comment]
ABAP-Swagger uses https://github.com/swagger-api/swagger-ui, so if its possible in there, it can be implemented

the UI is initialized at https://github.com/larshp/ABAP-Swagger/blob/1303ec6082d8f8a637366cae8ed45773d43055f7/src/zcl_swag.clas.abap#L405

**Comment by larshp** [comment]
actually, also try changing this part,

https://github.com/larshp/ABAP-Swagger/blob/339531ca9fb29d00b3d8ca8bddd91194806eb77d/src/zcl_swag_spec.clas.abap#L136

**Comment by All2in** [comment]
Thanks!
