### ISSUE TITLE
DATA: in definitions/model

### ISSUE THREAD

**Issue by BlackmanCC** [larshp/ABAP-Swagger#65]
The current implementation builds definitions/models as following:

```
definitions: {
    TY_STRUCTURE: {
          type: "object",
          properties: {
              DATA: {
                  type: "object",
                  properties: {
                      FOO: {
                           type: "string"
                      },
                      BAR: {
                           type: "string"
                      }
                  }
             }
          }
    }
}
```
There ist always a bracket with "DATA:", then "type: "object"" 

When I look at the swagger specification
https://swagger.io/specification/v2/

and the swagger petstore sample, i cannot find any DATA bracket.

Would it be better it it was like this?

```
definitions: {
    TY_STRUCTURE: {
          type: "object",
          properties: {
                      FOO: {
                           type: "string"
                      },
                      BAR: {
                           type: "string"
                      }
                  }
             }
          }
    }
}
```

What do you think?

**Comment by larshp** [comment]
see https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code, formatting will make above easier to read

**Comment by BlackmanCC** [comment]
@larshp Thanks for the hint. I think it is m ore readable now.

**Comment by BlackmanCC** [comment]
@larshp 
The coding where DATA is added can be found in ZCL_SWAG_SPEC->REPSPONSE
```
      lv_string = |"{ <ls_parameter>-type }":\{"type": "object","properties": \{"DATA": \{{ lv_type }\}\}\}|.
```

**Comment by BlackmanCC** [comment]
I think this is quite similar to #24 . I close this issue and continue with #24.
