### ISSUE TITLE
Request for "latest" tag

### ISSUE THREAD

**Issue by neooblaster** [larshp/ABAP-Swagger#68]
Hi @larshp ,

I would like to suggest you to create a "latest" tag.
By doing this, it's easier to get the repository in zip file instead of cloning the project on the computer, then making a ZIP file to import the project on another SAP which has no access to GitHub.

![image](https://user-images.githubusercontent.com/22078558/105333611-35e10380-5bd6-11eb-9a14-afcb4268fd13.png)

Thanks a lot for Library.

Kindly regards,
Nicolas D. @Neooblaster

**Comment by neooblaster** [comment]
Hello @larshp ,

My bad, I didn't know we can download ZIP file from there....
I see you made some modification on the class. Maybe you should introduce a code version to identify which version is install on SAP System. Currently, this class is implemented in Production for one our customer. That could help to maintain while take attention about potential further incompatibilities (regarding production implementations).

For my request, it's OK, I close the issue.

Thanks a lot for this very quick answer and for the work you done to provided Swagger under SAP.

Kindly Regards,
Nicolas D.

**Comment by larshp** [comment]
with ZIP its difficult

but it might be possible to use the last deserialized timestamp(toggle details), to determine when the last version was installed

in all cases, whats is installed is installed, it doesn't help the upgrading anyhow. I assume customers/users implement unit and integration tests to verify the installation works

![image](https://user-images.githubusercontent.com/5888506/105348076-1521a980-5be8-11eb-95dc-20bba1fca130.png)
