### ISSUE TITLE
method run of zcl_swag can pick up wrong method if method names are simular enough

### ISSUE THREAD

**Issue by arcanist123** [larshp/ABAP-Swagger#84]
assume you have method1 and method1_test
the current code is doing the following
FIND REGEX <ls_meta>-meta-url-regex IN lv_path.
https://github.com/larshp/ABAP-Swagger/blob/main/src/zcl_swag.clas.abap line 610
if can call method1 even though the handler for method1_test was called

**Comment by larshp** [comment]
thanks, pull requests welcome

**Comment by arcanist123** [comment]
I was stupid, just needed to play around the regex. In my case, since I have handlers as post methods, it was enough to add $ at the end of the regex to solve the issue above
